### ISSUE TITLE
Make the edit box wider

### ISSUE THREAD

**Issue by orschiro** [nathanwentworth/new-tab-links#2]
The currently narrow edit box doesn't provide a good overview on the content.

Can we make the box a bit wider so that URLs fit the screen and don't cause a line break?

![image](https://user-images.githubusercontent.com/170947/34466905-675b8ab0-eee3-11e7-966e-48b591aaa93e.png)

**Comment by nathanwentworth** [comment]
yes! i'll add that in soon. thank you!

**Comment by nathanwentworth** [comment]
just published an update with a wider and resizable text box (and other features)!

**Comment by orschiro** [comment]
Very nice. Thanks for the new features! :-)
