### ISSUE TITLE
Newline after column delimiter causes column to start one line lower than expected

### ISSUE THREAD

**Issue by grrttedwards** [nathanwentworth/new-tab-links#3]
Placing a newline after a column delimiter `---` causes the column to start one line lower than it should. See below:

With content
```
Col 1a
test.url url_asdf_1a
Col 1b
test.url url_asdf_1b
---
Col 2a
test.url url_asdf_2a
```
![screen shot 2018-09-24 at 9 53 57 am](https://user-images.githubusercontent.com/5453928/45956362-4d952680-bfe0-11e8-9af3-bbfe6e2e87cd.png)

With a newline after the column delimiter
```
Col 1a
test.url url_asdf_1a
Col 1b
test.url url_asdf_1b
---

Col 2a
test.url url_asdf_2a
```
![screen shot 2018-09-24 at 9 54 07 am](https://user-images.githubusercontent.com/5453928/45956373-51c14400-bfe0-11e8-902d-07b5ed24a10f.png)

Multiple newlines have the same effect as one newline and lower the column by one line.

**Comment by nathanwentworth** [comment]
Fixed in version 1.5! Now updated on Firefox and Chrome stores ;^)
